tags:
  - name: people
    description: people API


paths:
# [GET] people
  /people/:
    get:
      tags:
        - people
      summary: Get people list
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
  # [GET] users/id
  /people/{name}:
    get:
      tags:
        - people
      summary: Find person by name
      parameters:
        - name: name
          in: path
          description: Person name
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

schemes:
 - https
 - http
