tags:
  - name: people
    description: People API
  - name: house
    description: House API

paths:
# [GET] people
  /people/:
    get:
      tags:
        - people
      summary: Get people list
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
  # [GET] people/id
  /people/{id}:
    get:
      tags:
        - people
      summary: Find person by id
      parameters:
        - name: id
          in: path
          description: Person id
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        404:
          description: 'Not found'
        500:
          description: 'Server Error'

# [GET] house
/house/:
  get:
    tags:
      - house
    summary: Get house list
    responses:
      200:
        description: 'OK'
      500:
        description: 'Server Error'
# [GET] house/id
/house/{id}:
  get:
    tags:
      - house
    summary: Find house by id
    parameters:
      - name: id
        in: path
        description: House id
        required: true
        type: string
    responses:
      200:
        description: 'OK'
      404:
        description: 'Not found'
      500:
        description: 'Server Error'

schemes:
 - https
 - http
