import { People } from '../interfaces/people.interface';
const peopleModel: People[] = [
  {
    name: 'Hannah Abbott',
    role: 'student',
    house: 'Hufflepuff',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
  },
  {
    name: 'Bathsheda Babbling',
    role: 'Professor, Ancient Runes',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Ludo Bagman',
    role: 'Head, Department of Magical Games and Sports',
    ministryOfMagic: true,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Bathilda Bagshot',
    role: 'Author, A History Of Magic',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Katie Bell',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    boggart: 'Lord Voldemort',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Cuthbert Binns',
    role: 'Professor, History of Magic',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'ghost',
  },
  {
    name: 'Phineas Nigellus Black',
    role: '(Formerly) Headmaster of Hogwarts',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Regulus Black',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Sirius Black',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    alias: 'Padfoot',
    animagus: 'black dog',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Amelia Bones',
    role: 'Head, Department of Magical Law Enforcement',
    house: 'Hufflepuff',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: true,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Susan Bones',
    role: 'student',
    house: 'Hufflepuff',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
  },
  {
    name: 'Terry Boot',
    role: 'student',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Lavender Brown',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    boggart: 'rat',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Millicent Bulstrode',
    role: 'student',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
  },
  {
    name: 'Frank Bryce',
    role: 'Gardener, Riddle Family',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'muggle',
    species: 'human',
  },
  {
    name: 'Charity Burbage',
    role: 'Professor, Muggle Studies',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    boggart: 'Lord Voldemort',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Alecto Carrow',
    role: 'Professor, Muggle Studies',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Amycus Carrow',
    role: 'Professor, Dark Arts',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Reginald Cattermole',
    role: 'Employee, Magical Maintenance Department',
    ministryOfMagic: true,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Mary Cattermole',
    wand: 'Cherry, 8 3/4", unicorn hair',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Cho Chang',
    role: 'Student',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    patronus: 'swan',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Penelope Clearwater',
    role: 'Student',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    alias: 'Penny',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Michael Corner',
    role: 'Student',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
  },
  {
    name: 'Crabbe',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Vincent Crabbe',
    role: 'Student',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    boggart: 'Lord Voldemort',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Colin Creevey',
    role: 'Student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'muggle-born',
    species: 'human',
  },
  {
    name: 'Dennis Creevey',
    role: 'Student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'muggle-born',
    species: 'human',
  },
  {
    name: 'Dirk Cresswell',
    role: 'Head, Goblin Liason Office',
    ministryOfMagic: true,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'muggle-born',
    species: 'human',
  },
  {
    name: 'Bartemius Crouch Sr.',
    role: 'Head, Department of International Magical Cooperation',
    alias: 'Barty',
    ministryOfMagic: true,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Bartemius Crouch Jr.',
    alias: 'Barty',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'John Dawlish',
    role: 'Auror',
    ministryOfMagic: true,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Fleur Delacour',
    role: 'Student',
    school: 'Beauxbatons Academy of Magic',
    wand: 'Rosewood, 9 1/2", veela hair',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'quarter-villa',
    species: 'part-human',
  },
  {
    name: 'Gabrielle Delacour',
    role: 'Student',
    school: 'Beauxbatons Academy of Magic',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'quarter-villa',
    species: 'part-human',
  },
  {
    name: 'Dedalus Diggle',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Amos Diggory',
    role:
      'Employee, Department for the Regulation and Control of Magical Creatures',
    ministryOfMagic: true,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Cedric Diggory',
    role: 'Student',
    house: 'Hufflepuff',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    wand: 'Ash, 12 1/4", unicorn hair',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Elphias Doge',
    role: 'Special Advisor to the Wizengamot',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Antonin Dolohov',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Aberforth Dumbledore',
    role: "Owner, Hog's Head Inn",
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    alias: 'Ab',
    patronus: 'goat',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
  },
  {
    name: 'Albus Dumbledore',
    role: 'Headmaster, Hogwarts',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    wand: 'Elder, 15", thestral tail hair',
    boggart: 'Ariana (sister)',
    patronus: 'phoenix',
    ministryOfMagic: true,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
  },
  {
    name: 'Ariana Dumbledore',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
  },
  {
    name: 'Dudley Dursley',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'muggle',
    species: 'human',
  },
  {
    name: 'Marjorie Dursley',
    alias: 'Marge',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'muggle',
    species: 'human',
  },
  {
    name: 'Petunia Dursley',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'muggle',
    species: 'human',
  },
  {
    name: 'Vernon Dursley',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'muggle',
    species: 'human',
  },
  {
    name: 'Marietta Edgecombe',
    role: 'student',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Everard',
    role: '(former) Headmaster, Hogwarts',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Arabella Figg',
    role: 'Dealer of cross-bread cats and kneazies',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'squib',
    species: 'human',
  },
  {
    name: 'Argus Filch',
    role: 'Caretaker, Hogwarts',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'squib',
    species: 'human',
  },
  {
    name: 'Justin Finch-Fletchley',
    role: 'student',
    house: 'Hufflepuff',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    boggart: 'Lord Voldemort ',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Seamus Finnigan',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    boggart: 'banshee',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
  },
  {
    name: 'Marcus Flint',
    role: 'student',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Nicolas Flamel',
    role: 'Alchemist',
    school: 'Beauxbatons Academy of Magic',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Mundungus Fletcher',
    role: 'Dealer of Wizarding Artifacts',
    alias: 'Dung',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
  },
  {
    name: 'Filius Flitwick',
    role: 'Professor, Charms',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    boggart: 'Lord Voldemort',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'part-goblin',
  },
  {
    name: 'Cornelius Fudge',
    role: 'Minister of Magic',
    ministryOfMagic: true,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Marvolo Gaunt',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Merope Gaunt',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Morfin Gaunt',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Anthony Goldstein',
    role: 'student',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
  },
  {
    name: 'Goyle Sr.',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Gregory Goyle',
    role: 'student',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Hermione Granger',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    wand: 'Vine wood, 10 3/4", dragon heartstring',
    boggart: 'failure',
    patronus: 'otter',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'muggle-born',
    species: 'human',
  },
  {
    name: 'Mykew Gregorovitch',
    role: 'Wand Maker',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Fenrir Greyback',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'unknown',
    species: 'werewolf',
  },
  {
    name: 'Gellert Grindelwald',
    school: 'Durmstrang Institute',
    alias: 'Percival Graves',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Wilhelmina Grubbly-Plank',
    role: 'Professor, Care of Magical Creatures',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Godric Gryffindor',
    role: 'Founder, Hogwarts',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Rubeus Hagrid',
    role: 'Groundkeeper, Professor, Care of Magical Creatures',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    wand: 'Oak, 16", unknown core',
    boggart: 'Lord Voldemort',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'half-giant',
  },
  {
    name: 'Rolanda Hooch',
    role: 'Quidditch Referee ',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Mafalda Hopkirk',
    role: 'Assistant, mproper Use of Magic Office',
    ministryOfMagic: true,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Helga Hufflepuff',
    role: 'Founder, Hogwarts',
    house: 'Hufflepuff',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Angelina Johnson',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Lee Jordan',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    alias: 'River',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Bertha Jorkins',
    role: 'Department of Magical Games and Sports Employee',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: true,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Igor Karkaroff',
    role: 'Headmaster, Durmstrang',
    school: 'Durmstrang Institute',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Viktor Krum',
    role: 'Bulgarian Quiddich Seeker',
    school: 'Durmstrang Institute',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Bellatrix Lestrange',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    alias: 'Bella',
    wand: 'Walnut, 10 3/4", dragon heartstring',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Rabastan Lestrange',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Rodolphus Lestrange',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Gilderoy Lockhart',
    role: 'Professor, Defense Against the Dark Arts',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    wand: 'Cherry, 9", dragon heartstring',
    boggart: 'cornish pixies',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
  },
  {
    name: 'Alice Longbottom',
    role: 'Auror (formerly)',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Frank Longbottom',
    role: 'Auror (formerly)',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Augusta Longbottom',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Neville Longbottom',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    wand: 'Cherry, 13", unicorn hair',
    boggart: 'Severus Snape',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Luna Lovegood',
    role: 'student',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    alias: 'Loony Lovegood',
    patronus: 'hare',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Xenophilius Lovegood',
    role: 'Editor, The Quibbler',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    alias: 'Xeno',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Remus Lupin',
    role: 'Professor, Defence Against the Dark Arts',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    alias: 'Moony',
    wand: 'Cypress, 10 1/4", unicorn hair',
    boggart: 'full moon',
    patronus: 'wolf',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'werewolf',
  },
  {
    name: 'Walden Macnair',
    role: 'Executioner, Committee of Disposal of Dangerous Creatures',
    ministryOfMagic: true,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Draco Malfoy',
    role: 'student',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    wand: 'Hawthorn, 10", unicorn hair',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Lucius Malfoy',
    role: 'School Governer of Hogwarts',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Narcissa Malfoy',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Madam Malkin',
    role: "Shop Owner, Madam Malkin's Robes for All Occasions",
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Olympe Maxime',
    role: 'Headmistress, Beauxbatons Academy of Magic',
    school: 'Beauxbatons Academy of Magic',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'half-giant',
    species: 'half-giant',
  },
  {
    name: 'Ernest Macmillan',
    role: 'student',
    house: 'Hufflepuff',
    school: 'Hogwarts Academy of Witchcraft and Wizardry',
    alias: 'Ernie',
    boggart: 'Lord Voldemort',
    patronus: 'boar',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Minerva McGonagall',
    role: 'Professor, Transfiguration',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    wand: 'Fir, 9 1/2", dragon heartstring',
    boggart: 'Lord Voldemort',
    patronus: 'cat',
    animagus: 'tabby cat',
    ministryOfMagic: true,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
  },
  {
    name: 'Alastor Moody',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    alias: 'Mad-Eye',
    ministryOfMagic: true,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Theodore Nott',
    role: 'student',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Garrick Ollivander',
    role: 'Wandmaker',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    wand: 'Hornbeam, 12 3/4", dragon heartstring',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
  },
  {
    name: 'Pansy Parkinson',
    role: 'student',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Padma Patil',
    role: 'student',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Parvati Patil',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    boggart: 'mummy',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Peter Pettigrew',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    alias: 'Wormtail',
    wand: 'Chestnut, 9 1/4, dragon heartstring',
    boggart: 'Lord Voldemort',
    animagus: 'rat',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Antioch Peverell',
    wand: 'Elder, 15", Thestral tail hair core',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Cadmus Peverell',
    role: 'Owner of the resurrection stone',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Ignotus Peverell',
    role: 'Owner of the invisibility cloak',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Irma Pince',
    role: 'Librarian, Hogwarts',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    boggart: 'Lord Voldemort',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Sturgis Podmore',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Poppy Pomfrey',
    role: 'Matron, Hogwarts Hospital Wing',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Harry Potter',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    alias: 'The Boy Who Lived',
    wand: 'Holly, 11", phoenix feather',
    boggart: 'dementor',
    patronus: 'stag',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
  },
  {
    name: 'James Potter I',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    alias: 'Prongs',
    wand: 'Mahogany, 11", unknown core',
    patronus: 'stag',
    animagus: 'stag',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Lily J. Potter',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    wand: 'Willow, 10 1/4", unknown core',
    patronus: 'doe',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'muggle-born',
    species: 'human',
  },
  {
    name: 'Ernest Prang',
    role: 'Driver of the Knight Bus',
    alias: 'Ernie',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Quirinus Quirrell',
    role: 'Professor, Defence Against the Dark Arts',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    wand: 'Alder, 9", unicorn hair',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
  },
  {
    name: 'Helena Ravenclaw',
    role: 'Ravenclaw House Ghost',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    alias: 'Grey Lady',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'ghost',
  },
  {
    name: 'Rowena Ravenclaw',
    role: 'Founder, Hogwarts',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Mary Riddle',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'muggle',
    species: 'human',
  },
  {
    name: 'Thomas Riddle',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'muggle',
    species: 'human',
  },
  {
    name: 'Tom Riddle Sr',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'muggle',
    species: 'human',
  },
  {
    name: 'Tom Riddle',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    alias: 'Lord Voldemort',
    wand: 'Yew, 13 1/2", phoenix feather core',
    boggart: 'his own corpse',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'half-blood',
    species: 'human',
  },
  {
    name: 'Demelza Robins',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Augustus Rockwood',
    role: 'Unspeakable',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Albert Runcorn',
    ministryOfMagic: true,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Scabior',
    role: 'Snatcher',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Newton Scamander ',
    role: 'Author, Fantastic Beasts and Where to Find Them',
    house: 'Hufflepuff',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    alias: 'Newt ',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Rufus Scrimgeour',
    role: 'Head of Auror Office',
    ministryOfMagic: true,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Kingsley Shacklebolt',
    role: 'Auror',
    patronus: 'lynx',
    ministryOfMagic: true,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Stanley Shunpike',
    role: 'Conductor of the Knight Bus',
    alias: 'Stan ',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Aurora Sinistra',
    role: 'Professor, Astronomy',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Rita Skeeter',
    role: 'Gossip Correspondant for the Daily Prophet',
    alias: 'Queen of the Quills',
    animagus: 'beetle',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Horace Slughorn',
    role: 'Professor, Potions',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    wand: 'Cedar, 10 1/4", dragon heartstring',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Salazar Slytherin',
    role: 'Founder, Hogwarts',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Hepzibah Smith',
    house: 'Hufflepuff',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Zacharias Smith',
    role: 'student',
    house: 'Hufflepuff',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Severus Snape',
    role: 'Professor, Potions',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    patronus: 'doe',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'half-blood',
    species: 'human',
  },
  {
    name: 'Alicia Spinnet',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Pomona Sprout',
    role: 'Professor, Herbology',
    house: 'Hufflepuff',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Pius Thicknesse',
    ministryOfMagic: true,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Dean Thomas',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    boggart: "severed hand walking on it's own",
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
  },
  {
    name: 'Andromeda Tonks',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Nymphadora Tonks',
    role: 'Auror',
    house: 'Hufflepuff',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    alias: 'Tonks',
    patronus: 'wolf',
    ministryOfMagic: true,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human (metamorphmagus)',
  },
  {
    name: 'Edward Tonks',
    alias: 'Ted',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'muggle-born',
    species: 'human',
  },
  {
    name: 'Travers',
    role: 'Ministry of Magic Official',
    ministryOfMagic: true,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Sybill Trelawney',
    role: 'Professor, Divination',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    wand: 'Hazel, 9 1/2", unicorn hair',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
  },
  {
    name: 'Dolores Umbridge',
    role: 'Head of the Muggle Born Registration Commission',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    wand: 'Birch, 8", dragon heartstring',
    patronus: 'persian cat',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'half-blood',
    species: 'human',
  },
  {
    name: 'Emmeline Vance',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Romilda Vane',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Septima Vector',
    role: 'Professor, Arithmancy',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Arthur Weasley',
    role: 'Head, Misuse of Muggle Artifacts ',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    patronus: 'weasel',
    ministryOfMagic: true,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'William Weasley',
    role: 'Curse Breaker, Gringotts Bank',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    alias: 'Bill',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Charles Weasley',
    role: 'Dragonologist',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    alias: 'Charlie',
    wand: 'Ash, 12", unicorn hair tail',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Fred Weasley',
    role: "co-owner of Weasleys' Wizard Wheezes",
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'George Weasley',
    role: "co-owner of Weasleys' Wizard Wheezes",
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Ginevra Weasley',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    alias: 'Ginny',
    patronus: 'horse',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Molly Weasley',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    boggart: 'corpses of her family',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Percy Weasley',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Ronald Weasley',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    alias: 'Ron',
    wand: 'Willow, 14", unicorn hair tail',
    boggart: 'Aragog',
    patronus: 'jack russell terrier',
    ministryOfMagic: false,
    orderOfThePhoenix: true,
    dumbledoresArmy: true,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Oliver Wood',
    role: 'student',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Kennilworthy Whisp',
    role: 'Author, Quiddich Through The Ages',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Corban Yaxley',
    ministryOfMagic: true,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: true,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Blaise Zabini',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Aragog',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'acromantula',
  },
  {
    name: 'Bane',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'centaur',
  },
  {
    name: 'Beedle the Bard',
    role: 'Fairytale Author',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Bloody Baron',
    role: 'Slytherin House Ghost',
    house: 'Slytherin',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'ghost',
  },
  {
    name: 'Buckbeak',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'hippogriff',
  },
  {
    name: 'Cadogan',
    role: 'Gryffindor Tower Door Guard',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'pure-blood',
    species: 'human',
  },
  {
    name: 'Crookshanks',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'cat',
  },
  {
    name: 'Dobby',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'house-elf',
  },
  {
    name: 'Errol',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'Great Grey Owl',
  },
  {
    name: 'Fang',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'Boarhound',
  },
  {
    name: 'Fat Friar',
    role: 'Hufflepuff House Ghost',
    house: 'Hufflepuff',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'ghost',
  },
  {
    name: 'Fridfwulfa',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'giant',
  },
  {
    name: 'Fat Lady',
    role: 'Gryffindor Tower Door Guard',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'portrait',
  },
  {
    name: 'Fawkes',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'phoenix',
  },
  {
    name: 'Firenze',
    role: 'Professor, Divination',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'centaur',
  },
  {
    name: 'Fluffy',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'three-headed dog',
  },
  {
    name: 'Grawp',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'giant',
  },
  {
    name: 'Griphook',
    role: 'Employee, Gringotts Wizarding Bank',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'goblin',
  },
  {
    name: 'Hedwig',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'Snowy Owl',
  },
  {
    name: 'Hokey',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'house-elf',
  },
  {
    name: 'Kreacher',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'house-elf',
  },
  {
    name: 'Magorian',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'centaur',
  },
  {
    name: 'Myrtle Warren',
    role: 'student',
    house: 'Ravenclaw',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    alias: 'Moaning Myrtle',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'muggle-born',
    species: 'ghost',
  },
  {
    name: 'Mrs. Norris',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'cat',
  },
  {
    name: 'Great Aunt Muriel',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Nagini',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'horcrux',
  },
  {
    name: 'Nicholas de Mimsy-Porpington',
    role: 'Gryffindor House Ghost',
    house: 'Gryffindor',
    school: 'Hogwarts School of Witchcraft and Wizardry',
    alias: 'Nearly Headless Nick',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'ghost',
  },
  {
    name: 'Norbert',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'Norwegian Ridgeback',
  },
  {
    name: 'Peeves',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'poltergeist',
  },
  {
    name: 'Pigwidgeon',
    alias: 'Pig',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'scops owl',
  },
  {
    name: 'Madam Rosmerta',
    role: 'Owner, The Three Broomsticks',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'human',
  },
  {
    name: 'Ronan',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'centaur',
  },
  {
    name: 'Trevor',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'toad',
  },
  {
    name: 'Winky',
    ministryOfMagic: false,
    orderOfThePhoenix: false,
    dumbledoresArmy: false,
    deathEater: false,
    bloodStatus: 'unknown',
    species: 'house-elf',
  },
];
export default peopleModel;
